version: "3.8"

services:
  web:
    image: darshinih/flask_proj
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=flaskdb
      - DB_USER=flaskuser
      - DB_PASSWORD=flaskpass
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: