name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # Logs into Docker Hub using credentials stored in GitHub Secrets, allowing for subsequent image push actions.
          
    - name: Build and Push Image
      uses: docker/build-push-action@v4
      with:
        context: .
        #file: /Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/flask_proj:latest
